version: '3.4'

services:
  #######################################################
  # BACKEND #############################################
  #######################################################
  backend:
    # name the image so that it cannot be found in a DockerHub repository, otherwise it will not be built locally from the 'dockerfile' but pulled from there
    image: it4c/backend:local-development
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      # This makes sure the docker container has its own node modules.
      # Therefore it is possible to have a different node version on the host machine
      - backend_node_modules:/server/node_modules
      # bind the local folder to the docker to allow live reload
      - ./:/server

volumes:
  backend_node_modules:
  documentation_node_modules:
