version: '3.4'

services:
  #######################################################
  # BACKEND #############################################
  #######################################################
  backend:
    # name the image so that it cannot be found in a DockerHub repository, otherwise it will not be built locally from the 'dockerfile' but pulled from there
    image: it4c/backend:local-test
    build:
      context: .
      target: test
    networks:
      - external-net
      - internal-net
    ports:
      - 4000:4000
    environment:
      # Envs used in Dockerfile
      # - DOCKER_WORKDIR="/server"
      # - PORT=4000
      # - BUILD_DATE="1970-01-01T00:00:00.00Z"
      # - BUILD_VERSION="0.0.0.0"
      # - BUILD_COMMIT="0000000"
      - NODE_ENV=test

networks:
  external-net:
  internal-net:
    internal: true
